version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
  commands:
    - echo Installing dependencies...
    - npm install -g serverless
    - npm install
  build:
    commands:
      - echo Building the serverless project...
      - serverless deploy --stage dev
artifacts:
  files:
    - '**/*'
