---
version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Packaging the application...
      - zip -r function.zip handler.js node_modules package.json
        package-lock.json
artifacts:
  files:
    - function.zip
  name: SourceArtifact
