version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20 # Match the Node.js version
    commands:
      - npm install
  build:
    commands:
      - zip -r function.zip handler.js node_modules package.json package-lock.json
artifacts:
  files:
    - function.zip
  name: BuildArtifact
