version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20 # Match the Node.js version
    commands:
      - npm install
  build:
    commands:
     - zip -r function.zip handler.js node_modules package.json package-lock.json
  args: "lambda update-function-code \
    --function-name arn:aws:lambda:ap-south-1:886436936280:function:egg-dep \
    --zip-file fileb://code.zip"   
artifacts:
  files:
    - function.zip
  name: SourceArtifact
