version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Cleaning npm cache...
      - npm cache clean --force
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - serverless deploy --stage prod

