version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing Serverless Framework...
      - npm install -g serverless
      - echo Verifying Serverless Framework installation...
      - serverless --version
      - echo Installing project dependencies...
      - npm install
  build:
    commands:
      - echo Deploying with Serverless Framework...
      - npx serverless deploy --stage prod

artifacts:
  files:
    - '**/*'

