service: my-backend-service

provider:
  name: aws
  runtime: nodejs16.x
  region: ap-south-1
  environment:
    NODE_ENV: production

functions:
  api:
    handler: handler.api
    events:
      - http:
          path: api
          method: get

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
