service: my-backend-service
provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1
functions:
  api:
    handler: handler.api
    events:
      - http:
          path: /
          method: get
