version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - npm config set maxsockets 50
      - npm install -g serverless
      - npm install
  build:
    commands:
      - echo Building the serverless project...
      - serverless deploy --stage prod
artifacts:
  files:
    - '**/*'
cache:
  paths:
    - '/root/.npm'
